name: Commitlint

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: scripts/prepare-pr-msg.sh
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
